# Generated by Django 4.2 on 2025-11-11 05:21

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Заголовок статьи')),
                ('title_ru', models.CharField(max_length=155, null=True, verbose_name='Заголовок статьи')),
                ('title_en', models.CharField(max_length=155, null=True, verbose_name='Заголовок статьи')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Содержание статьи')),
                ('description_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Содержание статьи')),
                ('description_en', ckeditor.fields.RichTextField(null=True, verbose_name='Содержание статьи')),
            ],
            options={
                'verbose_name': 'Статья блога',
                'verbose_name_plural': 'Блог',
            },
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=155, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(max_length=155, null=True, verbose_name='Заголовок')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('description_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Описание')),
                ('description_en', ckeditor.fields.RichTextField(null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Направление',
                'verbose_name_plural': 'Направления',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Имя пользователя')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('phone', models.CharField(max_length=25, verbose_name='Номер телефона')),
                ('message', models.TextField(verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Сообщение обратной связи',
                'verbose_name_plural': 'Обратная связь',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='main', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Изображение галереи',
                'verbose_name_plural': 'Галерея',
            },
        ),
        migrations.CreateModel(
            name='PartnerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='partners', verbose_name='Логотип партнера')),
            ],
            options={
                'verbose_name': 'Партнер',
                'verbose_name_plural': 'Партнеры',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Имя клиента')),
                ('name_ru', models.CharField(max_length=155, null=True, verbose_name='Имя клиента')),
                ('name_en', models.CharField(max_length=155, null=True, verbose_name='Имя клиента')),
                ('date', models.CharField(max_length=155, verbose_name='Дата отзыва')),
                ('description', models.TextField(verbose_name='Текст отзыва')),
                ('description_ru', models.TextField(null=True, verbose_name='Текст отзыва')),
                ('description_en', models.TextField(null=True, verbose_name='Текст отзыва')),
                ('star', models.CharField(choices=[(1, '★☆☆☆☆ (1)'), (2, '★★☆☆☆ (2)'), (3, '★★★☆☆ (3)'), (4, '★★★★☆ (4)'), (5, '★★★★★ (5)')], max_length=25, verbose_name='Рейтинг')),
            ],
            options={
                'verbose_name': 'Отзыв клиента',
                'verbose_name_plural': 'Отзывы клиентов',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='logo/', verbose_name='Логотип сайта')),
                ('title', models.CharField(max_length=155, verbose_name='Заголовок главного баннера')),
                ('title_ru', models.CharField(max_length=155, null=True, verbose_name='Заголовок главного баннера')),
                ('title_en', models.CharField(max_length=155, null=True, verbose_name='Заголовок главного баннера')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание главного баннера')),
                ('description_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Описание главного баннера')),
                ('description_en', ckeditor.fields.RichTextField(null=True, verbose_name='Описание главного баннера')),
                ('image_back', models.ImageField(upload_to='main/', verbose_name='Фон главного баннера')),
                ('title_about', models.CharField(max_length=155, verbose_name='Заголовок раздела "О нас"')),
                ('title_about_ru', models.CharField(max_length=155, null=True, verbose_name='Заголовок раздела "О нас"')),
                ('title_about_en', models.CharField(max_length=155, null=True, verbose_name='Заголовок раздела "О нас"')),
                ('text1', models.CharField(max_length=255, verbose_name='Текст (правая сторона)')),
                ('text1_ru', models.CharField(max_length=255, null=True, verbose_name='Текст (правая сторона)')),
                ('text1_en', models.CharField(max_length=255, null=True, verbose_name='Текст (правая сторона)')),
                ('text2', models.CharField(max_length=255, verbose_name='Текст (левая сторона)')),
                ('text2_ru', models.CharField(max_length=255, null=True, verbose_name='Текст (левая сторона)')),
                ('text2_en', models.CharField(max_length=255, null=True, verbose_name='Текст (левая сторона)')),
                ('image_about', models.ImageField(upload_to='main/', verbose_name='Фото раздела "О нас"')),
                ('logo_about', models.ImageField(upload_to='main/', verbose_name='Логотип в разделе "О нас"')),
                ('image_about_blok', models.ImageField(upload_to='main/', verbose_name='Фото блока о нас (1)')),
                ('image_about_blok2', models.ImageField(upload_to='main/', verbose_name='Фото блока о нас (2)')),
                ('description_about', ckeditor.fields.RichTextField(verbose_name='Описание блока "О нас" (1)')),
                ('description_about_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Описание блока "О нас" (1)')),
                ('description_about_en', ckeditor.fields.RichTextField(null=True, verbose_name='Описание блока "О нас" (1)')),
                ('description_about2', ckeditor.fields.RichTextField(verbose_name='Описание блока "О нас" (2)')),
                ('description_about2_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Описание блока "О нас" (2)')),
                ('description_about2_en', ckeditor.fields.RichTextField(null=True, verbose_name='Описание блока "О нас" (2)')),
                ('values', models.CharField(max_length=155, verbose_name='Заголовок блока "Ценности"')),
                ('values_ru', models.CharField(max_length=155, null=True, verbose_name='Заголовок блока "Ценности"')),
                ('values_en', models.CharField(max_length=155, null=True, verbose_name='Заголовок блока "Ценности"')),
                ('title_missions', models.CharField(max_length=155, verbose_name='Заголовок блока "Миссия"')),
                ('title_missions_ru', models.CharField(max_length=155, null=True, verbose_name='Заголовок блока "Миссия"')),
                ('title_missions_en', models.CharField(max_length=155, null=True, verbose_name='Заголовок блока "Миссия"')),
                ('description_missions', ckeditor.fields.RichTextField(verbose_name='Описание миссии')),
                ('description_missions_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Описание миссии')),
                ('description_missions_en', ckeditor.fields.RichTextField(null=True, verbose_name='Описание миссии')),
                ('title_directions', models.CharField(max_length=155, verbose_name='Заголовок блока "Направления"')),
                ('title_directions_ru', models.CharField(max_length=155, null=True, verbose_name='Заголовок блока "Направления"')),
                ('title_directions_en', models.CharField(max_length=155, null=True, verbose_name='Заголовок блока "Направления"')),
                ('title_development', models.CharField(max_length=155, verbose_name='Заголовок блока "Развитие"')),
                ('title_development_ru', models.CharField(max_length=155, null=True, verbose_name='Заголовок блока "Развитие"')),
                ('title_development_en', models.CharField(max_length=155, null=True, verbose_name='Заголовок блока "Развитие"')),
                ('description_development', ckeditor.fields.RichTextField(verbose_name='Описание блока "Развитие"')),
                ('description_development_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Описание блока "Развитие"')),
                ('description_development_en', ckeditor.fields.RichTextField(null=True, verbose_name='Описание блока "Развитие"')),
                ('title_parrners', models.CharField(max_length=155, verbose_name='Заголовок блока "Партнеры"')),
                ('title_parrners_ru', models.CharField(max_length=155, null=True, verbose_name='Заголовок блока "Партнеры"')),
                ('title_parrners_en', models.CharField(max_length=155, null=True, verbose_name='Заголовок блока "Партнеры"')),
                ('title_reviews', models.CharField(max_length=155, verbose_name='Заголовок блока "Отзывы"')),
                ('title_reviews_ru', models.CharField(max_length=155, null=True, verbose_name='Заголовок блока "Отзывы"')),
                ('title_reviews_en', models.CharField(max_length=155, null=True, verbose_name='Заголовок блока "Отзывы"')),
                ('title_blog', models.CharField(max_length=155, verbose_name='Заголовок блока "Блог"')),
                ('title_blog_ru', models.CharField(max_length=155, null=True, verbose_name='Заголовок блока "Блог"')),
                ('title_blog_en', models.CharField(max_length=155, null=True, verbose_name='Заголовок блока "Блог"')),
                ('description_blog', ckeditor.fields.RichTextField(verbose_name='Описание блока "Блог"')),
                ('description_blog_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Описание блока "Блог"')),
                ('description_blog_en', ckeditor.fields.RichTextField(null=True, verbose_name='Описание блока "Блог"')),
                ('title_end', models.CharField(max_length=155, verbose_name='Заголовок блока "Готовы к путешествию"')),
                ('title_end_ru', models.CharField(max_length=155, null=True, verbose_name='Заголовок блока "Готовы к путешествию"')),
                ('title_end_en', models.CharField(max_length=155, null=True, verbose_name='Заголовок блока "Готовы к путешествию"')),
                ('image_end', models.ImageField(upload_to='main/', verbose_name='Фото блока "Готовы к путешествию"')),
                ('title_feedback', models.CharField(max_length=155, verbose_name='Заголовок формы обратной связи')),
                ('title_feedback_ru', models.CharField(max_length=155, null=True, verbose_name='Заголовок формы обратной связи')),
                ('title_feedback_en', models.CharField(max_length=155, null=True, verbose_name='Заголовок формы обратной связи')),
                ('description_feedback', ckeditor.fields.RichTextField(verbose_name='Описание формы обратной связи')),
                ('description_feedback_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Описание формы обратной связи')),
                ('description_feedback_en', ckeditor.fields.RichTextField(null=True, verbose_name='Описание формы обратной связи')),
                ('title_contact', models.CharField(max_length=155, verbose_name='Заголовок блока "Контакты"')),
                ('title_contact_ru', models.CharField(max_length=155, null=True, verbose_name='Заголовок блока "Контакты"')),
                ('title_contact_en', models.CharField(max_length=155, null=True, verbose_name='Заголовок блока "Контакты"')),
                ('phone_number', models.CharField(max_length=25, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта администратора')),
                ('address', ckeditor.fields.RichTextField(verbose_name='Адрес')),
                ('address_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Адрес')),
                ('address_en', ckeditor.fields.RichTextField(null=True, verbose_name='Адрес')),
                ('text', models.CharField(max_length=155, verbose_name='Наименование компании')),
                ('text_ru', models.CharField(max_length=155, null=True, verbose_name='Наименование компании')),
                ('text_en', models.CharField(max_length=155, null=True, verbose_name='Наименование компании')),
                ('end_text', models.CharField(max_length=350, verbose_name='Текст нижней части сайта')),
                ('end_text_ru', models.CharField(max_length=350, null=True, verbose_name='Текст нижней части сайта')),
                ('end_text_en', models.CharField(max_length=350, null=True, verbose_name='Текст нижней части сайта')),
            ],
            options={
                'verbose_name': 'Главные настройки сайта',
                'verbose_name_plural': 'Главные настройки сайта',
            },
        ),
        migrations.CreateModel(
            name='Values',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=155, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(max_length=155, null=True, verbose_name='Заголовок')),
                ('image', models.ImageField(upload_to='values', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Ценность',
                'verbose_name_plural': 'Ценности компании',
            },
        ),
        migrations.CreateModel(
            name='DirectionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='direction', verbose_name='Фото')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direction', to='laiding.direction', verbose_name='Направление')),
            ],
            options={
                'verbose_name': 'Фото направления',
                'verbose_name_plural': 'Фото направлений',
            },
        ),
    ]
