# Generated by Django 4.2 on 2025-11-17 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laiding', '0002_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(max_length=155, verbose_name='Тип')),
                ('types_ru', models.CharField(max_length=155, null=True, verbose_name='Тип')),
                ('types_en', models.CharField(max_length=155, null=True, verbose_name='Тип')),
                ('statistic', models.CharField(max_length=25, verbose_name='Статистика')),
            ],
        ),
        migrations.AddField(
            model_name='settings',
            name='inta',
            field=models.CharField(default=1, max_length=355, verbose_name='Ссылка на Инстаграм '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='telegram',
            field=models.CharField(default=1, max_length=355, verbose_name='Ссылка на Telegram '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='title_statistic',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='settings',
            name='watchap',
            field=models.CharField(default=1, max_length=355, verbose_name='Ссылка на Ватсап '),
            preserve_default=False,
        ),
    ]
