# Generated by Django 4.2 on 2025-11-17 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laiding', '0003_statistic_settings_inta_settings_telegram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='star',
            field=models.CharField(blank=True, choices=[(1, '★☆☆☆☆ (1)'), (2, '★★☆☆☆ (2)'), (3, '★★★☆☆ (3)'), (4, '★★★★☆ (4)'), (5, '★★★★★ (5)')], max_length=25, null=True, verbose_name='Рейтинг'),
        ),
    ]
