# Generated by Django 4.2 on 2025-11-17 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laiding', '0005_alter_reviews_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='star',
            field=models.CharField(blank=True, help_text='Максимум 5 звезд', max_length=25, null=True, verbose_name='Рейтинг'),
        ),
    ]
