# Generated by Django 4.2 on 2025-11-17 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laiding', '0006_alter_reviews_star'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='description_parrners',
            field=models.CharField(default=1, max_length=355, verbose_name='Описание Партнера'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='description_parrners_en',
            field=models.CharField(max_length=355, null=True, verbose_name='Описание Партнера'),
        ),
        migrations.AddField(
            model_name='settings',
            name='description_parrners_ru',
            field=models.CharField(max_length=355, null=True, verbose_name='Описание Партнера'),
        ),
        migrations.AddField(
            model_name='settings',
            name='title_statistic_en',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='settings',
            name='title_statistic_ru',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовок'),
        ),
    ]
